#ifndef NETWORK_CONFIGURATION_H
#define NETWORK_CONFIGURATION_H

#define NETWORK_LAYER_NUM (3)
#define NETWORK_CONFIGURATION {4, 1000, 1}

#define NETWORK_EPOCHS (1)
#define NETWORK_GAMMA (0.5)
#define NETWORK_ALPHA (0.2)

#define THREAD_NUM (8)

#endif  // NETWORK_CONFIGURATION_H
