#ifndef NETWORK_CONFIGURATION_H
#define NETWORK_CONFIGURATION_H

#define NETWORK_LAYER_NUM (4)
#define NETWORK_CONFIGURATION {4, 8, 12, 1}

#define NETWORK_EPOCHS (20000)
#define NETWORK_GAMMA (0.2)
#define NETWORK_ALPHA (0.1)

#define THREAD_NUM (8)

#endif  // NETWORK_CONFIGURATION_H
